/*
 * This file is generated by jOOQ.
*/
package com.example.db;


import com.example.db.tables.Building;
import com.example.db.tables.FingerprinterInfo;
import com.example.db.tables.Room;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in location_indoor
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>location_indoor.building</code>.
     */
    public static final Building BUILDING = com.example.db.tables.Building.BUILDING;

    /**
     * The table <code>location_indoor.fingerprinter_info</code>.
     */
    public static final FingerprinterInfo FINGERPRINTER_INFO = com.example.db.tables.FingerprinterInfo.FINGERPRINTER_INFO;

    /**
     * The table <code>location_indoor.room</code>.
     */
    public static final Room ROOM = com.example.db.tables.Room.ROOM;
}
