/*
 * This file is generated by jOOQ.
*/
package com.uet.fingerpinter.db.tables.records;


import com.uet.fingerpinter.db.tables.FingerprinterInfoDetail;
import com.uet.fingerpinter.jooq.type.TypeFingerprinterInfo;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FingerprinterInfoDetailRecord extends UpdatableRecordImpl<FingerprinterInfoDetailRecord> implements Record4<Integer, Integer, Double, TypeFingerprinterInfo> {

    private static final long serialVersionUID = 1366460087;

    /**
     * Setter for <code>public.fingerprinter_info_detail.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.fingerprinter_info_detail.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.fingerprinter_info_detail.reference_id</code>.
     */
    public void setReferenceId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.fingerprinter_info_detail.reference_id</code>.
     */
    public Integer getReferenceId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.fingerprinter_info_detail.rss</code>.
     */
    public void setRss(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.fingerprinter_info_detail.rss</code>.
     */
    public Double getRss() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>public.fingerprinter_info_detail.type</code>.
     */
    public void setType(TypeFingerprinterInfo value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.fingerprinter_info_detail.type</code>.
     */
    public TypeFingerprinterInfo getType() {
        return (TypeFingerprinterInfo) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Double, TypeFingerprinterInfo> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Double, TypeFingerprinterInfo> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return FingerprinterInfoDetail.FINGERPRINTER_INFO_DETAIL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return FingerprinterInfoDetail.FINGERPRINTER_INFO_DETAIL.REFERENCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return FingerprinterInfoDetail.FINGERPRINTER_INFO_DETAIL.RSS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<TypeFingerprinterInfo> field4() {
        return FingerprinterInfoDetail.FINGERPRINTER_INFO_DETAIL.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getReferenceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getRss();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeFingerprinterInfo value4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FingerprinterInfoDetailRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FingerprinterInfoDetailRecord value2(Integer value) {
        setReferenceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FingerprinterInfoDetailRecord value3(Double value) {
        setRss(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FingerprinterInfoDetailRecord value4(TypeFingerprinterInfo value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FingerprinterInfoDetailRecord values(Integer value1, Integer value2, Double value3, TypeFingerprinterInfo value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FingerprinterInfoDetailRecord
     */
    public FingerprinterInfoDetailRecord() {
        super(FingerprinterInfoDetail.FINGERPRINTER_INFO_DETAIL);
    }

    /**
     * Create a detached, initialised FingerprinterInfoDetailRecord
     */
    public FingerprinterInfoDetailRecord(Integer id, Integer referenceId, Double rss, TypeFingerprinterInfo type) {
        super(FingerprinterInfoDetail.FINGERPRINTER_INFO_DETAIL);

        set(0, id);
        set(1, referenceId);
        set(2, rss);
        set(3, type);
    }
}
