/*
 * This file is generated by jOOQ.
*/
package com.uet.fingerpinter.db.tables.records;


import com.uet.fingerpinter.db.tables.FingerprinterTracking;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FingerprinterTrackingRecord extends UpdatableRecordImpl<FingerprinterTrackingRecord> implements Record6<Integer, Integer, Integer, Double, String, String> {

    private static final long serialVersionUID = -1589305991;

    /**
     * Setter for <code>public.fingerprinter_tracking.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.fingerprinter_tracking.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.fingerprinter_tracking.session_id</code>.
     */
    public void setSessionId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.fingerprinter_tracking.session_id</code>.
     */
    public Integer getSessionId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.fingerprinter_tracking.index</code>.
     */
    public void setIndex(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.fingerprinter_tracking.index</code>.
     */
    public Integer getIndex() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.fingerprinter_tracking.rss</code>.
     */
    public void setRss(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.fingerprinter_tracking.rss</code>.
     */
    public Double getRss() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>public.fingerprinter_tracking.mac_address</code>.
     */
    public void setMacAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.fingerprinter_tracking.mac_address</code>.
     */
    public String getMacAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.fingerprinter_tracking.ap_name</code>.
     */
    public void setApName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.fingerprinter_tracking.ap_name</code>.
     */
    public String getApName() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Double, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Double, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return FingerprinterTracking.FINGERPRINTER_TRACKING.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return FingerprinterTracking.FINGERPRINTER_TRACKING.SESSION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return FingerprinterTracking.FINGERPRINTER_TRACKING.INDEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return FingerprinterTracking.FINGERPRINTER_TRACKING.RSS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return FingerprinterTracking.FINGERPRINTER_TRACKING.MAC_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return FingerprinterTracking.FINGERPRINTER_TRACKING.AP_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSessionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getRss();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMacAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getApName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FingerprinterTrackingRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FingerprinterTrackingRecord value2(Integer value) {
        setSessionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FingerprinterTrackingRecord value3(Integer value) {
        setIndex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FingerprinterTrackingRecord value4(Double value) {
        setRss(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FingerprinterTrackingRecord value5(String value) {
        setMacAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FingerprinterTrackingRecord value6(String value) {
        setApName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FingerprinterTrackingRecord values(Integer value1, Integer value2, Integer value3, Double value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FingerprinterTrackingRecord
     */
    public FingerprinterTrackingRecord() {
        super(FingerprinterTracking.FINGERPRINTER_TRACKING);
    }

    /**
     * Create a detached, initialised FingerprinterTrackingRecord
     */
    public FingerprinterTrackingRecord(Integer id, Integer sessionId, Integer index, Double rss, String macAddress, String apName) {
        super(FingerprinterTracking.FINGERPRINTER_TRACKING);

        set(0, id);
        set(1, sessionId);
        set(2, index);
        set(3, rss);
        set(4, macAddress);
        set(5, apName);
    }
}
