/*
 * This file is generated by jOOQ.
*/
package com.uet.fingerpinter.db;


import com.uet.fingerpinter.db.tables.Building;
import com.uet.fingerpinter.db.tables.FingerprinterInfo;
import com.uet.fingerpinter.db.tables.FingerprinterInfoDetail;
import com.uet.fingerpinter.db.tables.FingerprinterInfoGauss;
import com.uet.fingerpinter.db.tables.Room;
import com.uet.fingerpinter.db.tables.SessionTracking;
import com.uet.fingerpinter.db.tables.TrackReal;
import com.uet.fingerpinter.db.tables.Tracking;
import com.uet.fingerpinter.db.tables.TrackingKNearest;
import com.uet.fingerpinter.db.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 2138653006;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.building</code>.
     */
    public final Building BUILDING = com.uet.fingerpinter.db.tables.Building.BUILDING;

    /**
     * The table <code>public.fingerprinter_info</code>.
     */
    public final FingerprinterInfo FINGERPRINTER_INFO = com.uet.fingerpinter.db.tables.FingerprinterInfo.FINGERPRINTER_INFO;

    /**
     * The table <code>public.fingerprinter_info_detail</code>.
     */
    public final FingerprinterInfoDetail FINGERPRINTER_INFO_DETAIL = com.uet.fingerpinter.db.tables.FingerprinterInfoDetail.FINGERPRINTER_INFO_DETAIL;

    /**
     * The table <code>public.fingerprinter_info_gauss</code>.
     */
    public final FingerprinterInfoGauss FINGERPRINTER_INFO_GAUSS = com.uet.fingerpinter.db.tables.FingerprinterInfoGauss.FINGERPRINTER_INFO_GAUSS;

    /**
     * The table <code>public.room</code>.
     */
    public final Room ROOM = com.uet.fingerpinter.db.tables.Room.ROOM;

    /**
     * The table <code>public.session_tracking</code>.
     */
    public final SessionTracking SESSION_TRACKING = com.uet.fingerpinter.db.tables.SessionTracking.SESSION_TRACKING;

    /**
     * The table <code>public.track_real</code>.
     */
    public final TrackReal TRACK_REAL = com.uet.fingerpinter.db.tables.TrackReal.TRACK_REAL;

    /**
     * The table <code>public.tracking</code>.
     */
    public final Tracking TRACKING = com.uet.fingerpinter.db.tables.Tracking.TRACKING;

    /**
     * The table <code>public.tracking_k_nearest</code>.
     */
    public final TrackingKNearest TRACKING_K_NEAREST = com.uet.fingerpinter.db.tables.TrackingKNearest.TRACKING_K_NEAREST;

    /**
     * The table <code>public.user</code>.
     */
    public final User USER = com.uet.fingerpinter.db.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.BUILDING_ID_SEQ,
            Sequences.FINGERPRINTER_INFO_DETAIL_ID_SEQ,
            Sequences.FINGERPRINTER_INFO_GAUSS_ID_SEQ,
            Sequences.FINGERPRINTER_INFO_ID_SEQ,
            Sequences.ROOM_ID_SEQ,
            Sequences.SESSION_TRACKING_ID_SEQ,
            Sequences.TRACKING_ID_SEQ,
            Sequences.TRACKING_K_NEAREST_ID_SEQ,
            Sequences.TRACK_REAL_ID_SEQ,
            Sequences.USER_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Building.BUILDING,
            FingerprinterInfo.FINGERPRINTER_INFO,
            FingerprinterInfoDetail.FINGERPRINTER_INFO_DETAIL,
            FingerprinterInfoGauss.FINGERPRINTER_INFO_GAUSS,
            Room.ROOM,
            SessionTracking.SESSION_TRACKING,
            TrackReal.TRACK_REAL,
            Tracking.TRACKING,
            TrackingKNearest.TRACKING_K_NEAREST,
            User.USER);
    }
}
