/*
 * This file is generated by jOOQ.
*/
package com.uet.fingerpinter.db;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.building_id_seq</code>
     */
    public static final Sequence<Long> BUILDING_ID_SEQ = new SequenceImpl<Long>("building_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.fingerprinter_info_detail_id_seq</code>
     */
    public static final Sequence<Long> FINGERPRINTER_INFO_DETAIL_ID_SEQ = new SequenceImpl<Long>("fingerprinter_info_detail_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.fingerprinter_info_gauss_id_seq</code>
     */
    public static final Sequence<Long> FINGERPRINTER_INFO_GAUSS_ID_SEQ = new SequenceImpl<Long>("fingerprinter_info_gauss_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.fingerprinter_info_id_seq</code>
     */
    public static final Sequence<Long> FINGERPRINTER_INFO_ID_SEQ = new SequenceImpl<Long>("fingerprinter_info_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.room_id_seq</code>
     */
    public static final Sequence<Long> ROOM_ID_SEQ = new SequenceImpl<Long>("room_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.session_tracking_id_seq</code>
     */
    public static final Sequence<Long> SESSION_TRACKING_ID_SEQ = new SequenceImpl<Long>("session_tracking_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.tracking_id_seq</code>
     */
    public static final Sequence<Long> TRACKING_ID_SEQ = new SequenceImpl<Long>("tracking_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.tracking_k_nearest_id_seq</code>
     */
    public static final Sequence<Long> TRACKING_K_NEAREST_ID_SEQ = new SequenceImpl<Long>("tracking_k_nearest_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.track_real_id_seq</code>
     */
    public static final Sequence<Long> TRACK_REAL_ID_SEQ = new SequenceImpl<Long>("track_real_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.user_id_seq</code>
     */
    public static final Sequence<Long> USER_ID_SEQ = new SequenceImpl<Long>("user_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
