/*
 * This file is generated by jOOQ.
*/
package com.uet.fingerpinter.db;


import com.uet.fingerpinter.db.tables.Building;
import com.uet.fingerpinter.db.tables.FingerprinterInfo;
import com.uet.fingerpinter.db.tables.FingerprinterInfoDetail;
import com.uet.fingerpinter.db.tables.FingerprinterInfoGauss;
import com.uet.fingerpinter.db.tables.FingerprinterTracking;
import com.uet.fingerpinter.db.tables.ResultTrackingDemo;
import com.uet.fingerpinter.db.tables.Room;
import com.uet.fingerpinter.db.tables.SessionTracking;
import com.uet.fingerpinter.db.tables.TrackReal;
import com.uet.fingerpinter.db.tables.Tracking;
import com.uet.fingerpinter.db.tables.TrackingKNearest;
import com.uet.fingerpinter.db.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in location_indoor
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>location_indoor.building</code>.
     */
    public static final Building BUILDING = com.uet.fingerpinter.db.tables.Building.BUILDING;

    /**
     * The table <code>location_indoor.fingerprinter_info</code>.
     */
    public static final FingerprinterInfo FINGERPRINTER_INFO = com.uet.fingerpinter.db.tables.FingerprinterInfo.FINGERPRINTER_INFO;

    /**
     * The table <code>location_indoor.fingerprinter_info_detail</code>.
     */
    public static final FingerprinterInfoDetail FINGERPRINTER_INFO_DETAIL = com.uet.fingerpinter.db.tables.FingerprinterInfoDetail.FINGERPRINTER_INFO_DETAIL;

    /**
     * The table <code>location_indoor.fingerprinter_info_gauss</code>.
     */
    public static final FingerprinterInfoGauss FINGERPRINTER_INFO_GAUSS = com.uet.fingerpinter.db.tables.FingerprinterInfoGauss.FINGERPRINTER_INFO_GAUSS;

    /**
     * The table <code>location_indoor.fingerprinter_tracking</code>.
     */
    public static final FingerprinterTracking FINGERPRINTER_TRACKING = com.uet.fingerpinter.db.tables.FingerprinterTracking.FINGERPRINTER_TRACKING;

    /**
     * The table <code>location_indoor.result_tracking_demo</code>.
     */
    public static final ResultTrackingDemo RESULT_TRACKING_DEMO = com.uet.fingerpinter.db.tables.ResultTrackingDemo.RESULT_TRACKING_DEMO;

    /**
     * The table <code>location_indoor.room</code>.
     */
    public static final Room ROOM = com.uet.fingerpinter.db.tables.Room.ROOM;

    /**
     * The table <code>location_indoor.session_tracking</code>.
     */
    public static final SessionTracking SESSION_TRACKING = com.uet.fingerpinter.db.tables.SessionTracking.SESSION_TRACKING;

    /**
     * The table <code>location_indoor.tracking</code>.
     */
    public static final Tracking TRACKING = com.uet.fingerpinter.db.tables.Tracking.TRACKING;

    /**
     * The table <code>location_indoor.tracking_k_nearest</code>.
     */
    public static final TrackingKNearest TRACKING_K_NEAREST = com.uet.fingerpinter.db.tables.TrackingKNearest.TRACKING_K_NEAREST;

    /**
     * The table <code>location_indoor.track_real</code>.
     */
    public static final TrackReal TRACK_REAL = com.uet.fingerpinter.db.tables.TrackReal.TRACK_REAL;

    /**
     * The table <code>location_indoor.user</code>.
     */
    public static final User USER = com.uet.fingerpinter.db.tables.User.USER;
}
