/*
 * This file is generated by jOOQ.
*/
package com.uet.fingerpinter.db.tables;


import com.uet.fingerpinter.db.Keys;
import com.uet.fingerpinter.db.Public;
import com.uet.fingerpinter.db.tables.records.BuildingRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Building extends TableImpl<BuildingRecord> {

    private static final long serialVersionUID = 414675051;

    /**
     * The reference instance of <code>public.building</code>
     */
    public static final Building BUILDING = new Building();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BuildingRecord> getRecordType() {
        return BuildingRecord.class;
    }

    /**
     * The column <code>public.building.id</code>.
     */
    public final TableField<BuildingRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('building_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.building.building_name</code>.
     */
    public final TableField<BuildingRecord, String> BUILDING_NAME = createField("building_name", org.jooq.impl.SQLDataType.VARCHAR.length(225).nullable(false), this, "");

    /**
     * The column <code>public.building.building_address</code>.
     */
    public final TableField<BuildingRecord, String> BUILDING_ADDRESS = createField("building_address", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * Create a <code>public.building</code> table reference
     */
    public Building() {
        this("building", null);
    }

    /**
     * Create an aliased <code>public.building</code> table reference
     */
    public Building(String alias) {
        this(alias, BUILDING);
    }

    private Building(String alias, Table<BuildingRecord> aliased) {
        this(alias, aliased, null);
    }

    private Building(String alias, Table<BuildingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<BuildingRecord, Integer> getIdentity() {
        return Keys.IDENTITY_BUILDING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BuildingRecord> getPrimaryKey() {
        return Keys.BUILDING_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BuildingRecord>> getKeys() {
        return Arrays.<UniqueKey<BuildingRecord>>asList(Keys.BUILDING_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Building as(String alias) {
        return new Building(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Building rename(String name) {
        return new Building(name, null);
    }
}
