/*
 * This file is generated by jOOQ.
*/
package com.uet.fingerpinter.db.tables;


import com.uet.fingerpinter.db.Keys;
import com.uet.fingerpinter.db.LocationIndoor;
import com.uet.fingerpinter.db.tables.records.FingerprinterInfoDetailRecord;
import com.uet.fingerpinter.jooq.convert.TypeFingerprinterInfoConvertter;
import com.uet.fingerpinter.jooq.type.TypeFingerprinterInfo;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FingerprinterInfoDetail extends TableImpl<FingerprinterInfoDetailRecord> {

    private static final long serialVersionUID = 1560521171;

    /**
     * The reference instance of <code>location_indoor.fingerprinter_info_detail</code>
     */
    public static final FingerprinterInfoDetail FINGERPRINTER_INFO_DETAIL = new FingerprinterInfoDetail();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FingerprinterInfoDetailRecord> getRecordType() {
        return FingerprinterInfoDetailRecord.class;
    }

    /**
     * The column <code>location_indoor.fingerprinter_info_detail.id</code>.
     */
    public final TableField<FingerprinterInfoDetailRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>location_indoor.fingerprinter_info_detail.reference_id</code>.
     */
    public final TableField<FingerprinterInfoDetailRecord, Integer> REFERENCE_ID = createField("reference_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>location_indoor.fingerprinter_info_detail.type</code>.
     */
    public final TableField<FingerprinterInfoDetailRecord, TypeFingerprinterInfo> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "", new TypeFingerprinterInfoConvertter());

    /**
     * The column <code>location_indoor.fingerprinter_info_detail.rss</code>.
     */
    public final TableField<FingerprinterInfoDetailRecord, Double> RSS = createField("rss", org.jooq.impl.SQLDataType.FLOAT.nullable(false), this, "");

    /**
     * Create a <code>location_indoor.fingerprinter_info_detail</code> table reference
     */
    public FingerprinterInfoDetail() {
        this("fingerprinter_info_detail", null);
    }

    /**
     * Create an aliased <code>location_indoor.fingerprinter_info_detail</code> table reference
     */
    public FingerprinterInfoDetail(String alias) {
        this(alias, FINGERPRINTER_INFO_DETAIL);
    }

    private FingerprinterInfoDetail(String alias, Table<FingerprinterInfoDetailRecord> aliased) {
        this(alias, aliased, null);
    }

    private FingerprinterInfoDetail(String alias, Table<FingerprinterInfoDetailRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return LocationIndoor.LOCATION_INDOOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<FingerprinterInfoDetailRecord, Integer> getIdentity() {
        return Keys.IDENTITY_FINGERPRINTER_INFO_DETAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<FingerprinterInfoDetailRecord> getPrimaryKey() {
        return Keys.KEY_FINGERPRINTER_INFO_DETAIL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<FingerprinterInfoDetailRecord>> getKeys() {
        return Arrays.<UniqueKey<FingerprinterInfoDetailRecord>>asList(Keys.KEY_FINGERPRINTER_INFO_DETAIL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FingerprinterInfoDetail as(String alias) {
        return new FingerprinterInfoDetail(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FingerprinterInfoDetail rename(String name) {
        return new FingerprinterInfoDetail(name, null);
    }
}
