/*
 * This file is generated by jOOQ.
*/
package com.uet.fingerpinter.db.tables;


import com.uet.fingerpinter.db.Keys;
import com.uet.fingerpinter.db.Public;
import com.uet.fingerpinter.db.tables.records.FingerprinterTrackingRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FingerprinterTracking extends TableImpl<FingerprinterTrackingRecord> {

    private static final long serialVersionUID = -48519836;

    /**
     * The reference instance of <code>public.fingerprinter_tracking</code>
     */
    public static final FingerprinterTracking FINGERPRINTER_TRACKING = new FingerprinterTracking();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FingerprinterTrackingRecord> getRecordType() {
        return FingerprinterTrackingRecord.class;
    }

    /**
     * The column <code>public.fingerprinter_tracking.id</code>.
     */
    public final TableField<FingerprinterTrackingRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('fingerprinter_tracking_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.fingerprinter_tracking.session_id</code>.
     */
    public final TableField<FingerprinterTrackingRecord, Integer> SESSION_ID = createField("session_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.fingerprinter_tracking.index</code>.
     */
    public final TableField<FingerprinterTrackingRecord, Integer> INDEX = createField("index", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.fingerprinter_tracking.rss</code>.
     */
    public final TableField<FingerprinterTrackingRecord, Double> RSS = createField("rss", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.fingerprinter_tracking.mac_address</code>.
     */
    public final TableField<FingerprinterTrackingRecord, String> MAC_ADDRESS = createField("mac_address", org.jooq.impl.SQLDataType.VARCHAR.length(1000).nullable(false), this, "");

    /**
     * The column <code>public.fingerprinter_tracking.ap_name</code>.
     */
    public final TableField<FingerprinterTrackingRecord, String> AP_NAME = createField("ap_name", org.jooq.impl.SQLDataType.VARCHAR.length(1000), this, "");

    /**
     * Create a <code>public.fingerprinter_tracking</code> table reference
     */
    public FingerprinterTracking() {
        this("fingerprinter_tracking", null);
    }

    /**
     * Create an aliased <code>public.fingerprinter_tracking</code> table reference
     */
    public FingerprinterTracking(String alias) {
        this(alias, FINGERPRINTER_TRACKING);
    }

    private FingerprinterTracking(String alias, Table<FingerprinterTrackingRecord> aliased) {
        this(alias, aliased, null);
    }

    private FingerprinterTracking(String alias, Table<FingerprinterTrackingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<FingerprinterTrackingRecord, Integer> getIdentity() {
        return Keys.IDENTITY_FINGERPRINTER_TRACKING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<FingerprinterTrackingRecord> getPrimaryKey() {
        return Keys.FINGERPRINTER_TRACKING_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<FingerprinterTrackingRecord>> getKeys() {
        return Arrays.<UniqueKey<FingerprinterTrackingRecord>>asList(Keys.FINGERPRINTER_TRACKING_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FingerprinterTracking as(String alias) {
        return new FingerprinterTracking(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FingerprinterTracking rename(String name) {
        return new FingerprinterTracking(name, null);
    }
}
