/*
 * This file is generated by jOOQ.
*/
package com.uet.fingerpinter.db.tables;


import com.uet.fingerpinter.db.Keys;
import com.uet.fingerpinter.db.Sql12200503;
import com.uet.fingerpinter.db.tables.records.FingerprinterInfoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FingerprinterInfo extends TableImpl<FingerprinterInfoRecord> {

    private static final long serialVersionUID = -631507704;

    /**
     * The reference instance of <code>sql12200503.fingerprinter_info</code>
     */
    public static final FingerprinterInfo FINGERPRINTER_INFO = new FingerprinterInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FingerprinterInfoRecord> getRecordType() {
        return FingerprinterInfoRecord.class;
    }

    /**
     * The column <code>sql12200503.fingerprinter_info.id</code>.
     */
    public final TableField<FingerprinterInfoRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sql12200503.fingerprinter_info.ap_name</code>.
     */
    public final TableField<FingerprinterInfoRecord, String> AP_NAME = createField("ap_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>sql12200503.fingerprinter_info.mac_address</code>.
     */
    public final TableField<FingerprinterInfoRecord, String> MAC_ADDRESS = createField("mac_address", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>sql12200503.fingerprinter_info.rss</code>.
     */
    public final TableField<FingerprinterInfoRecord, Double> RSS = createField("rss", org.jooq.impl.SQLDataType.FLOAT.nullable(false), this, "");

    /**
     * The column <code>sql12200503.fingerprinter_info.x</code>.
     */
    public final TableField<FingerprinterInfoRecord, Integer> X = createField("x", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sql12200503.fingerprinter_info.y</code>.
     */
    public final TableField<FingerprinterInfoRecord, Integer> Y = createField("y", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sql12200503.fingerprinter_info.room_id</code>.
     */
    public final TableField<FingerprinterInfoRecord, Integer> ROOM_ID = createField("room_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sql12200503.fingerprinter_info.building_id</code>.
     */
    public final TableField<FingerprinterInfoRecord, Integer> BUILDING_ID = createField("building_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>sql12200503.fingerprinter_info</code> table reference
     */
    public FingerprinterInfo() {
        this("fingerprinter_info", null);
    }

    /**
     * Create an aliased <code>sql12200503.fingerprinter_info</code> table reference
     */
    public FingerprinterInfo(String alias) {
        this(alias, FINGERPRINTER_INFO);
    }

    private FingerprinterInfo(String alias, Table<FingerprinterInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private FingerprinterInfo(String alias, Table<FingerprinterInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sql12200503.SQL12200503;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<FingerprinterInfoRecord, Integer> getIdentity() {
        return Keys.IDENTITY_FINGERPRINTER_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<FingerprinterInfoRecord> getPrimaryKey() {
        return Keys.KEY_FINGERPRINTER_INFO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<FingerprinterInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<FingerprinterInfoRecord>>asList(Keys.KEY_FINGERPRINTER_INFO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<FingerprinterInfoRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<FingerprinterInfoRecord, ?>>asList(Keys.FINGERPRINTER_INFO_2, Keys.FINGERPRINTER_INFO_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FingerprinterInfo as(String alias) {
        return new FingerprinterInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FingerprinterInfo rename(String name) {
        return new FingerprinterInfo(name, null);
    }
}
