/*
 * This file is generated by jOOQ.
*/
package com.uet.fingerpinter.db.tables;


import com.uet.fingerpinter.db.Keys;
import com.uet.fingerpinter.db.Public;
import com.uet.fingerpinter.db.tables.records.TrackRealRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrackReal extends TableImpl<TrackRealRecord> {

    private static final long serialVersionUID = -1078568511;

    /**
     * The reference instance of <code>public.track_real</code>
     */
    public static final TrackReal TRACK_REAL = new TrackReal();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TrackRealRecord> getRecordType() {
        return TrackRealRecord.class;
    }

    /**
     * The column <code>public.track_real.id</code>.
     */
    public final TableField<TrackRealRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('track_real_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.track_real.room_id</code>.
     */
    public final TableField<TrackRealRecord, Integer> ROOM_ID = createField("room_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.track_real.x</code>.
     */
    public final TableField<TrackRealRecord, Integer> X = createField("x", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.track_real.y</code>.
     */
    public final TableField<TrackRealRecord, Integer> Y = createField("y", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>public.track_real</code> table reference
     */
    public TrackReal() {
        this("track_real", null);
    }

    /**
     * Create an aliased <code>public.track_real</code> table reference
     */
    public TrackReal(String alias) {
        this(alias, TRACK_REAL);
    }

    private TrackReal(String alias, Table<TrackRealRecord> aliased) {
        this(alias, aliased, null);
    }

    private TrackReal(String alias, Table<TrackRealRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TrackRealRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TRACK_REAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TrackRealRecord> getPrimaryKey() {
        return Keys.TRACK_REAL_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TrackRealRecord>> getKeys() {
        return Arrays.<UniqueKey<TrackRealRecord>>asList(Keys.TRACK_REAL_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TrackRealRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TrackRealRecord, ?>>asList(Keys.TRACK_REAL__TRACK_REAL_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrackReal as(String alias) {
        return new TrackReal(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackReal rename(String name) {
        return new TrackReal(name, null);
    }
}
